#!/usr/bin/env ruby

"""
Problem 2
Even Fibonacci numbers
Published on 19 October 2001 at 06:00 pm [Server Time]

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

class Fib
  def initialize
    @mem = {0 => 0, 1 => 1, 2 => 2}
  end

  def calc(n)
    @mem[n] ||= calc(n-2) + calc(n-1)
  end
end

def main
  fib = Fib.new
  sum = 0
  n = 0
  loop do
    return sum if (nth = fib.calc(n)) >= 4000000
    sum += nth if nth%2 == 0
    n += 1
  end
end

puts main()
